<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Configuración del módulo de <strong>Marcadores</strong>' => '',
    'Volver a los modulos' => '',
    'Configuración de vista de marcadores' => '',
    'Aquí puede cambiar la configuración de vista para marcadores.' => '',
    'Color del icono' => '',
    'Seleccionar el color' => '',
    'Mostrar marcador-recuento entre llaves.' => '',
    'Mostrar un icono para cada entrada.' => '',
    'Mostrar vista de marcador global en todo el ancho.' => '',
    'Mostrar contenido anclado primero.' => '',
    'Orden de clasificación'=> '',
];
