<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<strong>Bookmark</strong> module configuration' => 'Configuración del módulo de <strong>Marcadores</strong>',
    'Back to modules' => 'Volver a los modulos',
    'Bookmark view settings' => 'Configuración de vista de marcadores',
    'Here you can change the view settings for bookmarks.' => 'Aquí puede cambiar la configuración de vista para marcadores.',
    'Icon color' => 'Color del icono',
    'Select color' => 'Seleccionar el color',
    'Show Bookmark-Count in braces.' => 'Mostrar marcador-recuento entre llaves.',
    'Show an icon for each entry.' => 'Mostrar un icono para cada entrada.',
    'Show global Bookmark-View in full width.' => 'Mostrar vista de marcador global en todo el ancho.',
    'Show pinned content first.' => 'Mostrar contenido anclado primero.',
    'Sort order'=> 'Orden de clasificación',
];
